# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-09-02 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='research_group',
            field=models.CharField(default=b'a', max_length=1),
        ),
    ]
